In [6]:
%pip install numpy

     -------------------------------------- 14.6/14.6 MB 470.1 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [7]:
import numpy as np

TASK 1
Create a 1D array of numbers from 0 to 9
2. Convert a 1D array to a 2D array with 2 rows
3. Write a NumPy program to create an array of the integers from 30 to 70.
4. Write a NumPy program to append values to the end of an array.

In [8]:
# Create a 1D array of numbers from 0 to 9
import numpy as np
arr= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
# TASK 2
# Convert a 1D array to a 2D array with 2 rows
#Using 1D array above for the convert

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = arr.reshape(2, 5)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
# Write a NumPy program to create an array of the integers from 30 to 70.
import numpy as np
array=np.arange(30,71)
print("Array of the integers from 30 to70")
print(array)


Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [12]:
# Write a NumPy program to append values to the end of an array.
import numpy as np
y = [1, 2, 3]
print("array:")
print(y)
y = np.append(y, [[4, 5, 6], [7, 8, 9]])
print("New appended values to the end of the array:")
print(y)

array:
[1, 2, 3]
New appended values to the end of the array:
[1 2 3 4 5 6 7 8 9]


Extension
1. Write a NumPy program to find the number of rows and columns of a given matrix.
2. Write a NumPy program to create an array of all the even integers from 30 to 70.
3. Write a NumPy program to convert a list and tuple into arrays.
4. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [2]:
# Write a NumPy program to find the number of rows and columns of a given matrix.
import numpy as np
x= np.arange(1,13).reshape((3, 4))
print( "matrix:")
print(x)
print("Number of rows and columns of matrix:")
print(x.shape)

matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Number of rows and columns of matrix:
(3, 4)


In [4]:
# Write a NumPy program to create an array of all the even integers from 30 to 70.
import numpy as np
array=np.arange(30,71,2)
print("Array of even integers from 30 to 70")
print(array) 

Array of even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [5]:
# Write a NumPy program to convert a list and tuple into arrays.
import numpy as np
my_list = [10, 20, 30, 40, 50, 60, 70, 80]
print("List to array: ")
print(np.asarray(my_list))
my_tuple = ([1, 2, 3], [4, 6, 8])
print("Tuple to array: ")
print(np.asarray(my_tuple))

List to array: 
[10 20 30 40 50 60 70 80]
Tuple to array: 
[[1 2 3]
 [4 6 8]]


In [6]:
# Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.
import numpy as np
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('Gina', 2, 50.5), ('Craig', 4, 55.5),('Rick', 5, 48.10), ('Rita', 3, 45.10)]
# create a structured array
students = np.array(students_details, dtype=data_type)   
print("Original array:")
print(students)
print("Sort by height")
print(np.sort(students, order='height'))   

Original array:
[(b'Gina', 2, 50.5) (b'Craig', 4, 55.5) (b'Rick', 5, 48.1)
 (b'Rita', 3, 45.1)]
Sort by height
[(b'Rita', 3, 45.1) (b'Rick', 5, 48.1) (b'Gina', 2, 50.5)
 (b'Craig', 4, 55.5)]


Task 2
1. Write a NumPy program to add, subtract, multiply, divide arguments elementwise.
2. Write a NumPy program to round elements of the array to the nearest integer.
3. Write a NumPy program to get true division of the element-wise array inputs.

In [7]:
# Write a NumPy program to add, subtract, multiply, divide arguments elementwise.
import numpy as np
print("Add:")
print(np.add(6.0, 2.0))
print("Subtract:")
print(np.subtract(6.0, 2.0))
print("Multiply:")
print(np.multiply(6.0, 2.0))
print("Divide:")
print(np.divide(6.0, 2.0))


Add:
8.0
Subtract:
4.0
Multiply:
12.0
Divide:
3.0


In [9]:
# Write a NumPy program to round elements of the array to the nearest integer.
import numpy as np
x = np.array([.6, -1.8, 2.7, 1.5, -1.7, 2.6, 1.0])
print("Original array:")
print(x)
x = np.rint(x)
print("Round elements of the array to the nearest integer:")
print(x)


Original array:
[ 0.6 -1.8  2.7  1.5 -1.7  2.6  1. ]
Round elements of the array to the nearest integer:
[ 1. -2.  3.  2. -2.  3.  1.]


In [10]:
# Write a NumPy program to get true division of the element-wise array inputs.
import numpy as np
y = np.arange(10)
print("array:")
print(y)
print("Division of the array inputs, element-wise:")
print(np.true_divide(y, 3))


array:
[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise:
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]
